<a href="https://colab.research.google.com/github/Anjaliii7/kindle_review_sentimental_analysis/blob/main/kindle_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files
uploaded=files.upload()

Saving all_kindle_review .csv to all_kindle_review  (1).csv


In [6]:
import pandas as pd
data = pd.read_csv('all_kindle_review .csv', encoding='latin1')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [7]:
data[['reviewText','rating']]

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [9]:
data.shape

(12000, 11)

In [8]:
data.isnull().sum()

Unnamed: 0.1       0
Unnamed: 0         0
asin               0
helpful            0
rating             0
reviewText         0
reviewTime         0
reviewerID         0
reviewerName      38
summary            2
unixReviewTime     0
dtype: int64

In [10]:
data['rating'].unique

<bound method Series.unique of 0        3
1        5
2        3
3        3
4        4
        ..
11995    4
11996    5
11997    3
11998    1
11999    3
Name: rating, Length: 12000, dtype: int64>

In [11]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [12]:
# data preprocessing and cleaning
# positive review is 1 and negative review is 0
data['rating']=data['rating'].apply(lambda x: 0 if x<3 else 1)

In [13]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       1   
1             1        5957  B002HJV4DE   [1, 1]       1   
2             2        9146  B002ZG96I4   [0, 0]       1   
3             3        7038  B002QHWOEU   [1, 3]       1   
4             4        1776  B001A06VJ8   [0, 1]       1   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [14]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [15]:
# lower all the cases
data['reviewText']=data['reviewText'].str.lower()

In [16]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       1   
1             1        5957  B002HJV4DE   [1, 1]       1   
2             2        9146  B002ZG96I4   [0, 0]       1   
3             3        7038  B002QHWOEU   [1, 3]       1   
4             4        1776  B001A06VJ8   [0, 1]       1   

                                          reviewText   reviewTime  \
0  jace rankin may be short, but he's nothing to ...   09 2, 2010   
1  great short read.  i didn't want to put it dow...   10 8, 2013   
2  i'll start by saying this is the first of four...  04 11, 2014   
3  aggie is angela lansbury who carries pocketboo...   07 5, 2014   
4  i did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [17]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [18]:
# removing all special characters
data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+',' ',x))


In [19]:
# removing all stopwords
data['reviewText']=data['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y.lower() not in stopwords.words('english')]))

In [20]:
# remove all url's
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r"http\S+", "", x))


In [21]:
# remove html tags
data['reviewText']=data['reviewText'].apply(lambda x: BeautifulSoup(x,'lxml').get_text())

In [22]:
# remove extra spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

In [23]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       1   
1             1        5957  B002HJV4DE   [1, 1]       1   
2             2        9146  B002ZG96I4   [0, 0]       1   
3             3        7038  B002QHWOEU   [1, 3]       1   
4             4        1776  B001A06VJ8   [0, 1]       1   

                                          reviewText   reviewTime  \
0  jace rankin may short nothing mess man hauled ...   09 2, 2010   
1  great short read want put read one sitting sex...   10 8, 2013   
2  start saying first four books expecting 34 con...  04 11, 2014   
3  aggie angela lansbury carries pocketbooks inst...   07 5, 2014   
4  expect type book library pleased find price right  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [24]:
# apply lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [25]:
Lemmatizer=WordNetLemmatizer()
data['reviewText']=data['reviewText'].apply(lambda x: " ".join([Lemmatizer.lemmatize(y) for y in x.split()]))

In [26]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data['reviewText'],data['rating'],test_size=0.2,random_state=0)

In [29]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
x_train_bow=bow.fit_transform(x_train).toarray()
x_test_bow=bow.transform(x_test).toarray()

In [27]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x_train_tfidf=tfidf.fit_transform(x_train).toarray()
x_test_tfidf=tfidf.transform(x_test).toarray()

In [30]:
x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
# naive bayes
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(x_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(x_train_tfidf,y_train)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [33]:
y_pred_bow=nb_model_bow.predict(x_test_bow)

In [34]:
y_pred_tfidf=nb_model_tfidf.predict(x_test_tfidf)

In [35]:
print("BOW Accuracy :",accuracy_score(y_test,y_pred_bow))

BOW Accuracy : 0.5895833333333333


In [36]:
confusion_matrix(y_test,y_pred_bow)

array([[549, 235],
       [750, 866]])

In [38]:
print("TF-IDF Accuracy :",accuracy_score(y_test,y_pred_tfidf))

TF-IDF Accuracy : 0.5945833333333334


In [37]:
confusion_matrix(y_test,y_pred_tfidf)

array([[529, 255],
       [718, 898]])

In [39]:
!pip install gensim numpy --upgrade --force-reinstall

  Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached numpy-2.3.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
  Using cached smart_open-7.3.0.post1-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
Using cached smart_open-7.3.0.post1-py3-none-any.whl (61 kB)
Using cached wrapt-1.17.2-cp311-cp311-manyl

In [47]:
#word2vec
from gensim.models import Word2Vec,KeyedVectors
tokenized_reviews = data['reviewText'].apply(lambda x: x.split())
model = Word2Vec(sentences=tokenized_reviews, vector_size=100, window=5, min_count=1)

In [61]:
def average_word2vec(tokens_list, vector, generate_missing=False, k=100):
    if len(tokens_list)<1:
        return np.zeros(k)
    if generate_missing:
        vectorized = [vector[word] if word in vector else np.random.rand(k) for word in tokens_list]
    else:
        vectorized = [vector[word] if word in vector else np.zeros(k) for word in tokens_list]
    length = len(vectorized)
    sum_vectors = sum(vec for vec in vectorized)
    return np.array(sum_vectors) / length

In [64]:
data['average_word2vec'] = tokenized_reviews.apply(lambda x: average_word2vec(x, model.wv, k=100))

In [52]:
model.wv.most_similar("kindle")

[('amazon', 0.9474318027496338),
 ('version', 0.9415121674537659),
 ('edition', 0.9287059307098389),
 ('electronically', 0.9255780577659607),
 ('price', 0.9151445031166077),
 ('ebook', 0.9146352410316467),
 ('download', 0.9135791659355164),
 ('available', 0.9078643918037415),
 ('listing', 0.9046033024787903),
 ('freebie', 0.9003711938858032)]

In [54]:
data['average_word2vec'].head()

0    jace rankin may short nothing mess man hauled ...
1    great short read want put read one sitting sex...
2    start saying first four book expecting 34 conc...
3    aggie angela lansbury carry pocketbook instead...
4    expect type book library pleased find price right
Name: average_word2vec, dtype: object

In [65]:
import numpy as np
x=np.array(data['average_word2vec'].values.tolist())

In [58]:
y=data['rating']

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [76]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [68]:
y_pred=lr.predict(x_test)

In [69]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [77]:
print("Accuracy :",accuracy_score(y_test,y_pred))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred))
print("Classification Report :\n",classification_report(y_test,y_pred))

Accuracy : 0.76875
Confusion Matrix :
 [[ 431  353]
 [ 202 1414]]
Classification Report :
               precision    recall  f1-score   support

           0       0.68      0.55      0.61       784
           1       0.80      0.88      0.84      1616

    accuracy                           0.77      2400
   macro avg       0.74      0.71      0.72      2400
weighted avg       0.76      0.77      0.76      2400



In [79]:
import numpy as np
x=np.array(data['average_word2vec'].values.tolist())

In [87]:
y=data['rating']

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [89]:
#XG boost classifier
from xgboost import XGBClassifier
xgb=XGBClassifier()

In [91]:
y_pred=xgb.fit(x_train, y_train).predict(x_test)

In [92]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [93]:
print("Accuracy :",accuracy_score(y_test,y_pred))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred))
print("Classification Report :\n",classification_report(y_test,y_pred))

Accuracy : 0.7566666666666667
Confusion Matrix :
 [[ 461  323]
 [ 261 1355]]
Classification Report :
               precision    recall  f1-score   support

           0       0.64      0.59      0.61       784
           1       0.81      0.84      0.82      1616

    accuracy                           0.76      2400
   macro avg       0.72      0.71      0.72      2400
weighted avg       0.75      0.76      0.75      2400



In [94]:
import numpy as np
x=np.array(data['average_word2vec'].values.tolist())

In [100]:
y=data['rating']

In [101]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [102]:
#svm
from sklearn.svm import SVC
svm=SVC()

In [103]:
y_pred=svm.fit(x_train, y_train).predict(x_test)

In [105]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [106]:
print("Accuracy :",accuracy_score(y_test,y_pred))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred))
print("Classification Report :\n",classification_report(y_test,y_pred))

Accuracy : 0.76375
Confusion Matrix :
 [[ 416  368]
 [ 199 1417]]
Classification Report :
               precision    recall  f1-score   support

           0       0.68      0.53      0.59       784
           1       0.79      0.88      0.83      1616

    accuracy                           0.76      2400
   macro avg       0.74      0.70      0.71      2400
weighted avg       0.76      0.76      0.76      2400

